In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report

---
\


### ***UPLOAD THE FILE***



---




In [ ]:
from google.colab import files
a =files.upload()

Saving pima-indians-diabetes.data.csv to pima-indians-diabetes.data.csv


---
\


### ***Read the dataset***

---



In [ ]:
df = pd.read_csv("pima-indians-diabetes.data.csv")
df.head()

calorie_intake  fat_percentage  sugar_values genetic_history  diabetes
0             148              72           156              no         1
1              85              66            93             yes         0
2             183              64           191              no         1
3              89              66            97             yes         0
4             137              40           145              no         1

In [ ]:
df.shape

(768, 5)

In [ ]:
df1=df.dropna()
df1.shape

(768, 5)

**CONVERT** **ALL** **VALUE** ***INTO*** **FLOAT**

In [ ]:
df1 = df1.astype(float)
df1.dtypes
df1

calorie_intake  fat_percentage  sugar_values  genetic_history  diabetes
0             148.0            72.0         156.0              0.0       1.0
1              85.0            66.0          93.0              1.0       0.0
2             183.0            64.0         191.0              0.0       1.0
3              89.0            66.0          97.0              1.0       0.0
4             137.0            40.0         145.0              0.0       1.0
..              ...             ...           ...              ...       ...
763           101.0            76.0         109.0              1.0       0.0
764           122.0            70.0         130.0              1.0       0.0
765           121.0            72.0         129.0              1.0       0.0
766           126.0            60.0         134.0              0.0       1.0
767            93.0            70.0         101.0              1.0       0.0

[768 rows x 5 columns]

---
\


# **Converting** **column** **to** **a** **binary** **value** 

---



In [ ]:
df1.genetic_history[df1.genetic_history == 'yes'] = 1
df1.genetic_history[df1.genetic_history == 'no'] = 0
df1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


calorie_intake  fat_percentage  sugar_values genetic_history  diabetes
0               148              72           156               0         1
1                85              66            93               1         0
2               183              64           191               0         1
3                89              66            97               1         0
4               137              40           145               0         1
..              ...             ...           ...             ...       ...
763             101              76           109               1         0
764             122              70           130               1         0
765             121              72           129               1         0
766             126              60           134               0         1
767              93              70           101               1         0

[768 rows x 5 columns]

# **SPLIT** **INTO** **TRAIN** & **TEST**

In [ ]:

from sklearn.model_selection import train_test_split

X=df1.iloc[:,0:4]  # in
y=df1.iloc[:,4] #dep

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 


In [ ]:

X=df1.iloc[:,0:4]  # in
y=df1.iloc[:,4] #dep

# **Random** **Forest** **MODEL**

In [ ]:

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train,y_train)


RandomForestClassifier()

In [ ]:
y_pred=model.predict(X_test)
y_pred

array([1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0.])

In [ ]:
df1.head()

calorie_intake  fat_percentage  sugar_values  genetic_history  diabetes
0           148.0            72.0         156.0              0.0       1.0
1            85.0            66.0          93.0              1.0       0.0
2           183.0            64.0         191.0              0.0       1.0
3            89.0            66.0          97.0              1.0       0.0
4           137.0            40.0         145.0              0.0       1.0

In [ ]:
model.score(X_test, y_test)
from sklearn.metrics import accuracy_score  
accuracy_score(y_test, y_pred)

1.0

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        98
         1.0       1.00      1.00      1.00        56

    accuracy                           1.00       154
   macro avg       1.00      1.00      1.00       154
weighted avg       1.00      1.00      1.00       154



In [ ]:
from sklearn.metrics import confusion_matrix  
print(confusion_matrix(y_test, y_pred))

[[98  0]
 [ 0 56]]


# **Accuracy**

In [ ]:
"""y_test_list = []
for x in y_test:
    y_test_list.append(x)"""

In [ ]:
# y_test.iloc[:,0:].values


In [ ]:
# pd.get_dummies(df, prefix=['col1', 'col2'])


In [ ]:
y_pred_df =pd.DataFrame({'Actual': list(y_test), 'Predicted': list(y_pred)})

In [ ]:
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_pred_df['Actual'],y_pred_df['Predicted'])
matrix


array([[98,  0],
       [ 0, 56]])

In [ ]:
TP = matrix[0][0]
TN = matrix[1][1]
FP = matrix[0][1]
FN = matrix[1][0]

Accuracy = (TP + TN)/(TP+TN+FP+FN) * 100

print('The accuracy of this model is : ', Accuracy)

The accuracy of this model is :  100.0
